{{- if not .Values.nfvo.lcm.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: nsso-lcm-credentials
  labels:
    app: {{ .Values.fullnameOverride }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  username: {{ .Values.nfvo.lcm.username | b64enc | quote }}
  password: {{ .Values.nfvo.lcm.password | b64enc | quote }}
  name: {{ .Values.nfvo.lcm.name | b64enc | quote }}
{{- end }}