apiVersion: apps/v1
kind: Deployment
metadata:
  name: nssoui
  labels:
    app.kubernetes.io/name: nssoui
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nssoui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nssoui
    spec:
      containers:
        - name: nssoui
          image: "{{ .Values.uiimage.repository }}:{{ .Values.uiimage.tag }}"
          imagePullPolicy: {{ .Values.uiimage.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name:  operator-nssoui-config-volume
              mountPath: /var/www/html/assets/env.js
              subPath: env.js
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: operator-nssoui-config-volume
          configMap:
            name: {{ .Release.Name }}-operator-nssoui-config-{{ .Values.role }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}